# Generated by Django 6.0.3 on 2026-04-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='attendance_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('attended', 'Attended'), ('not_attended', 'Not Attended')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='report',
            name='county',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='report',
            name='division',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='report',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='report',
            name='subcounty',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='report',
            name='sublocation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='report',
            name='ward',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
