# Generated by Django 6.0.3 on 2026-04-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_attendance_status_report_county_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='incident_type',
            field=models.CharField(choices=[('low_registration', 'Low Voter Registration'), ('intimidation', 'Voter Intimidation'), ('violence', 'Violence / Disruption'), ('bribery', 'Vote Buying / Bribery'), ('other', 'Other')], default='low_registration', max_length=20),
        ),
    ]
